openapi: 3.0.2
info:
  title: Credentials Service
  version: '2.0'
  license:
    name: MIT License
servers:
  - url: 'https://api.cloudinsight.alertlogic.com'
    description: production
    x-alertlogic-session-endpoint: true
  - url: 'https://api.cloudinsight.product.dev.alertlogic.com'
    description: integration
    x-alertlogic-session-endpoint: true
paths:
  '/credentials/v2/{account_id}/credentials/{credential_id}':
    get:
      summary: Get Credential
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/AWS-Credential'
                  - $ref: '#/components/schemas/Azure-AD-User'
                description: Credential object.
      operationId: get_credential
      security:
        - X-AIMS-Auth-Token: []
      description: Get Credentail Object for a given customer
    parameters:
      - schema:
          type: string
        name: account_id
        in: path
        required: true
      - schema:
          type: string
        name: credential_id
        in: path
        required: true
    delete:
      summary: Delete Credential
      operationId: delete_credential
      responses:
        '204':
          description: No Content
  '/credentials/v2/{account_id}/credentials':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: List of credentials objects.
                items:
                  anyOf:
                    - $ref: '#/components/schemas/AWS-Credential'
                    - $ref: '#/components/schemas/Azure-AD-User'
      operationId: list_credentials
      security:
        - X-AIMS-Auth-Token: []
      parameters: []
    parameters:
      - schema:
          type: string
        name: account_id
        in: path
        required: true
        description: AIMS Account ID
    post:
      summary: ''
      operationId: create_credential
      responses:
        '200':
          description: OK
      description: Create new credential
      security:
        - X-AIMS-Auth-Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: User-defined credential name
              properties:
                name:
                  type: string
                  description: User-defined credential name
                secrets:
                  oneOf:
                    - $ref: '#/components/schemas/AWSCredentialInfo'
                    - $ref: '#/components/schemas/AzureADUserInfo'
                  description: Credential secrets Object
              required:
                - name
                - secrets
        description: ''
components:
  schemas:
    AWS-Credential:
      title: AWS-Credential
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        secrets:
          type: object
          properties:
            type:
              type: string
            arn:
              type: string
            external_id:
              type: string
        created:
          type: object
          properties:
            by:
              type: string
            at:
              type: integer
    Azure-AD-User:
      title: Azure-AD-User
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        secrets:
          type: object
          properties:
            type:
              type: string
            ad_id:
              type: string
            username:
              type: string
        created:
          type: object
          properties:
            by:
              type: string
            at:
              type: integer
    AWSCredentialInfo:
      title: AWSCredentialInfo
      type: object
      description: AWS IAM Role Request Parameters
      properties:
        type:
          type: string
          default: aws_iam_role
          description: 'Credential type, must be aws_iam_role'
          enum:
            - aws_iam_role
        arn:
          type: string
          description: AWS IAM role ARN
      required:
        - type
        - arn
    AzureADUserInfo:
      title: AzureADUserInfo
      type: object
      properties:
        type:
          type: string
          description: 'Credential secrets type, must be azure_ad_user'
          enum:
            - azure_ad_user
        ad_id:
          type: string
          description: Azure Active Directory Identifier
        username:
          type: string
          description: Azure AD user name
        password:
          type: string
          description: Azure AD user password
      required:
        - type
        - ad_id
        - username
        - password
      description: Azure AD User Request Parameters
  securitySchemes:
    X-AIMS-Auth-Token:
      name: X-AIMS-Auth-Token
      type: apiKey
      in: header
      description: AIMS Authentication Token

